package com.xsquare.documentscanner.ui.theme

import androidx.compose.ui.graphics.Color


val LightPrimary = Color(color = 0xFF2979FF)
val LightOnPrimary = Color(color = 0xFFFFFFFF)
val LightPrimaryContainer = Color(color = 0xFF0F6DF3)
val LightOnPrimaryContainer = Color(color = 0xFFFEFCFF)
val LightInversePrimary = Color(color = 0xFFB0C6FF)
val LightSecondary = Color(color = 0xFF445D95)
val LightOnSecondary = Color(color = 0xFFFFFFFF)
val LightSecondaryContainer = Color(color = 0xFFA7C0FF)
val LightOnSecondaryContainer = Color(color = 0xFF344D84)
val LightTertiary = Color(color = 0xFF8E2CAE)
val LightOnTertiary = Color(color = 0xFFFFFFFF)
val LightTertiaryContainer = Color(color = 0xFFAA49CA)
val LightOnTertiaryContainer = Color(color = 0xFFFFFBFF)
val LightBackground = Color(color = 0xFFFFFBFE)
val LightOnBackground = Color(color = 0xFF1C1B1F)
val LightSurface = Color(color = 0xFFFAF8FF)
val LightOnSurface = Color(color = 0xFF191B23)
val LightSurfaceVariant = Color(color = 0xFFE7E0EC)
val LightOnSurfaceVariant = Color(color = 0xFF49454F)
val LightInverseSurface = Color(color = 0xFF2D3039)
val LightInverseOnSurface = Color(color = 0xFFEFF0FB)
val LightSurfaceTint = Color(color = 0xFF6750A4)
val LightError = Color(color = 0xFFBA1A1A)
val LightOnError = Color(color = 0xFFFFFFFF)
val LightErrorContainer = Color(color = 0xFFFFDAD6)
val LightOnErrorContainer = Color(color = 0xFF93000A)
val LightOutline = Color(color = 0xFF727786)
val LightOutlineVariant = Color(color = 0xFFC2C6D7)
val LightScrim = Color(color = 0xFF000000)
val LightSearchBarBackground = Color(color = 0xFFF4F0F9)
val LightSearchPlaceholderTextColor = Color(color = 0xFFA0A0A0)

val DarkPrimary = Color(color = 0xFFB0C6FF)
val DarkOnPrimary = Color(color = 0xFF002D6E)
val DarkPrimaryContainer = Color(color = 0xFF558DFF)
val DarkOnPrimaryContainer = Color(color = 0xFF00143A)
val DarkInversePrimary = Color(color = 0xFF0058CA)
val DarkSecondary = Color(color = 0xFFB0C6FF)
val DarkOnSecondary = Color(color = 0xFF102E64)
val DarkSecondaryContainer = Color(color = 0xFF2B457C)
val DarkOnSecondaryContainer = Color(color = 0xFF9CB4F2)
val DarkTertiary = Color(color = 0xFFF0B0FF)
val DarkOnTertiary = Color(color = 0xFF54006D)
val DarkTertiaryContainer = Color(color = 0xFFCA67E9)
val DarkOnTertiaryContainer = Color(color = 0xFF2B003A)
val DarkBackground = Color(color = 0xFF1C1B1F)
val DarkOnBackground = Color(color = 0xFFE6E1E5)
val DarkSurface = Color(color = 0xFF10131B)
val DarkOnSurface = Color(color = 0xFFE1E2ED)
val DarkSurfaceVariant = Color(color = 0xFF49454F)
val DarkOnSurfaceVariant = Color(color = 0xFFC2C6D7)
val DarkInverseSurface = Color(color = 0xFFE1E2ED)
val DarkInverseOnSurface = Color(color = 0xFF2D3039)
val DarkSurfaceTint = Color(color = 0xFFD0BCFF)
val DarkError = Color(color = 0xFFFFB4AB)
val DarkOnError = Color(color = 0xFF690005)
val DarkErrorContainer = Color(color = 0xFF93000A)
val DarkOnErrorContainer = Color(color = 0xFFFFDAD6)
val DarkOutline = Color(color = 0xFF8C90A0)
val DarkOutlineVariant = Color(color = 0xFF424655)
val DarkScrim = Color(color = 0xFF000000)